CREATE TABLE COMMENTS (
    ID SERIAL PRIMARY KEY,
    USER_ID INT NOT NULL,
    MOVIE_ID INT NOT NULL,
    DESCRIPTION VARCHAR(800) NOT NULL    
)
;

COPY COMMENTS(USER_ID,MOVIE_ID,DESCRIPTION) 
FROM '/docker-entrypoint-initdb.d/comments_data.csv' 
WITH CSV HEADER
;