CREATE TABLE MOVIES (
    ID SERIAL PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    DESCRIPTION VARCHAR(800) NOT NULL    
)
;

COPY MOVIES(NAME, DESCRIPTION) 
FROM '/docker-entrypoint-initdb.d/movies_data.csv' 
WITH CSV HEADER
;